### ISSUE TITLE
Code generation fails if markdown document does not contain front matter

### ISSUE THREAD

**Issue by haeussma** [JR-1991/md-models#3]
## Issue

When running `md-models convert` using a *.md data model, code generation fails. Although `validate` states that the document is valid.

## Example to reproduce

```md
# Calibration Standard Data Model

## Root objects

### Standard

- **molecule_id**
  - Type: string
  - Description: URI of the molecule (e.g. PubChem or ChEBI).
```

**Comment by JR-1991** [comment]
You have to add the front matter to the markdown model. You can copy it from one of the test cases found in the tests folder.
